version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-master
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_LISTEN_ADDRESS=cassandra-master
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_SEEDS=cassandra-master
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    networks:
      - cassandra_network
    ports:
      - "9042:9042"   # CQL
      - "7002:7000"   # Internode communication (mapped to different port)
      - "7003:7001"   # SSL Internode communication (mapped to different port)
      - "7199:7199"   # JMX
    volumes:
      - cassandra_data_master:/var/lib/cassandra

  slave:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-slave
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_LISTEN_ADDRESS=cassandra-slave
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_SEEDS=cassandra-master
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_READ_ONLY=true  # Mark this node as read-only
    networks:
      - cassandra_network
    ports:
      - "9043:9042"   # CQL (for read-only operations)
    depends_on:
      - master
    volumes:
      - cassandra_data_slave:/var/lib/cassandra

networks:
  cassandra_network:
    driver: bridge

volumes:
  cassandra_data_master:
  cassandra_data_slave:
