# Use the official MySQL image from the Docker Hub
FROM mysql:latest

# Set environment variables
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Expose the port MySQL runs on
EXPOSE 3306
